#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

REQUEST_CASES="${REQUEST_CASES:-8 10 100 1000 10000 100000}"
INCLUDE_1E6="${INCLUDE_1E6:-0}"
BODY_CASES="${BODY_CASES:-0}"
FIXED_CONCURRENCY="${FIXED_CONCURRENCY:-512}"
FIXED_REQUESTS="${FIXED_REQUESTS:-10000}"
CONCURRENCY_CASES="${CONCURRENCY_CASES:-8 64 128 512}"
WARMUP_PER_URL="${WARMUP_PER_URL:-512}"
RUN_GO_GATHER="${RUN_GO_GATHER:-0}"
H2_PORT="${H2_PORT:-8743}"
H1_PORT="${H1_PORT:-8745}"
H1_MAX_CONNECTIONS_PER_ORIGIN="${H1_MAX_CONNECTIONS_PER_ORIGIN:-256}"
CSV_FILE="${CSV_FILE:-}"

if [[ "$INCLUDE_1E6" == "1" && "$REQUEST_CASES" != *1000000* ]]; then
  REQUEST_CASES="$REQUEST_CASES 1000000"
fi

REQUEST_CASES="$REQUEST_CASES" \
BODY_CASES="$BODY_CASES" \
FIXED_CONCURRENCY="$FIXED_CONCURRENCY" \
FIXED_REQUESTS="$FIXED_REQUESTS" \
CONCURRENCY_CASES="$CONCURRENCY_CASES" \
WARMUP_PER_URL="$WARMUP_PER_URL" \
RUN_GO_GATHER="$RUN_GO_GATHER" \
H2_PORT="$H2_PORT" \
H1_PORT="$H1_PORT" \
H1_MAX_CONNECTIONS_PER_ORIGIN="$H1_MAX_CONNECTIONS_PER_ORIGIN" \
CSV_FILE="$CSV_FILE" \
  "$ROOT_DIR/scripts/run_resource_trend_bench.sh"
